// Generated by CoffeeScript 1.4.0
(function() {
  var addStyle;

  addStyle = function() {
    var style;
    console.log("Adding Big Netflix Style");
    style = document.createElement('link');
    style.type = 'text/css';
    style.href = chrome.extension.getURL('big-netflix.css');
    style.rel = 'stylesheet';
    document.head.appendChild(style);
    return console.log("Big Netflix Style Added");
  };

  addStyle();

}).call(this);
